##################################
# Generated by Log Parser Studio #
##################################

#Name: Server 2008 Failed Logon
#Log Type: EVTLOG
#Generated: 8/30/2013 11:26:47 PM

Param(
    [parameter(Mandatory=$false,ValueFromPipeline=$true)]
    [Bool]$AutoOpen,
	[parameter(Mandatory=$false,ValueFromPipeline=$true)]
    [String]$OutFile,
	[parameter(Mandatory=$false,ValueFromPipeline=$true)]
    [Bool]$IgnoreInParams,
	[parameter(Mandatory=$false,ValueFromPipeline=$true)]
    [Bool]$IgnoreOutParams) 
	
$Error.Clear()
$DefaultFolder=[Environment]::GetFolderPath("MyDocuments")
$Destination = "SERVER01 Server 2008 Failed Logon Archived Logs.CSV"
$Destination = $DefaultFolder + "\" + $Destination

if($OutFile -ne [String]::Empty)
{
	$OutFileType = [System.IO.Path]::GetExtension($OutFile.ToUpper())
	$OriginalFileType = [System.IO.Path]::GetExtension($Destination.ToUpper())
	if($OutFileType -ne $OriginalFileType)
	{
		Write-Host "You have chosen" $OutFileType "as the output, but this script was originally generated as" $OriginalFileType -ForegroundColor Red
		Write-Host "Either change -OutFile to" $OriginalFileType "or generate the script again with the output as" $OutFileType  -ForegroundColor Red
		Write-Host "You can also modify the OutputFormat variable in this script to match the correct Log Parser 2.2 COM output format." -ForegroundColor Red
		[System.Environment]::NewLine
		return
	}
	else
	{
		if($true -ne $OutFile.Contains("\"))
		{
		  $Destination = $DefaultFolder + "\" + $OutFile
		}
		else
		{
		  $Destination = $OutFile
		}
	}
}

$LogQuery = New-Object -ComObject "MSUtil.LogQuery"
$InputFormat = New-Object -ComObject "MSUtil.LogQuery.EventLogInputFormat"
$OutputFormat = New-Object -ComObject "MSUtil.LogQuery.CSVOutputFormat"

if($IgnoreInParams-eq $false){
     $InputFormat.fullText=1
     $InputFormat.resolveSIDs=0
     $InputFormat.formatMsg=1
     $InputFormat.msgErrorMode="MSG"
     $InputFormat.fullEventCode=0
     $InputFormat.direction="FW"
     $InputFormat.stringsSep="|"
     $InputFormat.binaryFormat="PRINT"
     $InputFormat.ignoreMessageErrors=1
}

if($IgnoreOutParams -eq $false){
     $OutputFormat.Headers="AUTO"
     $OutputFormat.oDQuotes="AUTO"
     $OutputFormat.tabs="OFF"
     $OutputFormat.oTsFormat="yyyy-MM-dd hh:mm:ss"
     $OutputFormat.oCodepage=0
     $OutputFormat.fileMode=1
}
Write-Progress -Activity "Executing query, please wait..."  -Status " "

$SQLQuery = "SELECT timegenerated, EXTRACT_TOKEN(Strings,5,'|') AS AccountName, EXTRACT_TOKEN(Strings,2,'|') AS AccountDomain, EXTRACT_TOKEN(Strings,19,'|') AS SourceIP, EventID  INTO '" + $Destination + "' FROM 'X:\Logs\*.evtx' WHERE EventID=4625 ORDER BY timegenerated"
$rtnVal = $LogQuery.ExecuteBatch($SQLQuery, $InputFormat, $OutputFormat);
$OutputFormat = $null;
$InputFormat = $null;
$LogQuery = $null;

if($AutoOpen)
{
	try
	{
		Start-Process($Destination)
	}
	catch
	{
		Write-Host $_.Exception.Message  -ForegroundColor Red
		Write-Host $_.Exception.GetType().FullName  -ForegroundColor Red
		Write-Host "NOTE: No output file will be created if the query returned zero records!"  -ForegroundColor Gray
	}	
}
